### ISSUE TITLE
Add programme custom post type

### ISSUE THREAD

**Issue by johnwheal** [nestcommunity/wordpress-theme#1]
This will have the following fields:
- Name
- Content
- Cover image?

**Comment by drphilipely** [comment]
Programmes I see going into a generic template which allows for headlines, body copy, paragraph formatting (bullets) and image insertion with a height and width limit perhaps. Not all programmes/services will have a logo though many probably will (e.g. Route to Startup does but Enterprise Clinic doesn't).
