### ISSUE TITLE
Add resources custom post type

### ISSUE THREAD

**Issue by johnwheal** [nestcommunity/wordpress-theme#2]
This will have the following fields:
- Title
- Link
- Brief Description

**Comment by drphilipely** [comment]
Add 'Image' or 'Logo' field (perhaps 150 x 150 logo. 

Would like to make this more like Startup Stash/Product Hunt where we see a tiled visual under certain categories. 
Ability to create categories would be good - so there's a top-level of things like 'Funding' , 'Development Tools', Marketing Tools' etc that would build up incrementally over a year
